### ISSUE TITLE
Hitching when placing or removing blocks

### ISSUE THREAD

**Issue by Chinguuuu** [embeddedt/ModernFix#126]
I've noticed when placing or removing a block, (grass in this case), there is a noticeable hitch. Persistently removing and placing a block quickly, the framerate reports significantly lower frames as a result of the hitching. I removed the mod and noticed no recognizable hitching but I could be wrong.

Edit: Unfortunately in my limited testing, it seems the problem persists regardless of whether ModernFix is installed or not. I would welcome any feedback regarding a fix but otherwise, I think this issue should be considered closed. Sorry about that.

**Comment by embeddedt** [comment]
Not sure why this would happen, but can you install the Spark mod, run a
client profile with /sparkc profiler and quickly spam placing/removing a
block for a few seconds?

**Comment by Chinguuuu** [comment]
Sure, here it is. I was spamming breaking placing a dirt block in one space for 30 seconds. https://spark.lucko.me/XCWg2hMzws

Also, here is the TPS graph before:

![image](https://github.com/embeddedt/ModernFix/assets/132147202/457609e2-b696-42cf-8620-fefae9ce23b7)

Here it is while breaking and placing. I understand if this is not the right place to ask for support. Feel free to close this issue whenever.

![image](https://github.com/embeddedt/ModernFix/assets/132147202/b2d3c4d2-51b7-4688-ad63-8073b6fb8d9f)

I tried without the particles and it was still the same.

**Comment by embeddedt** [comment]
> Unfortunately in my limited testing, it seems the problem persists regardless of whether ModernFix is installed or not. I would welcome any feedback regarding a fix but otherwise, I think this issue should be considered closed. Sorry about that.

You can try enabling Sodium's "Always Defer Chunk Updates" option. The reason this issue occurs is that the game attempts to immediately re-render the chunk if you break a block nearby, instead of deferring the work to another thread (which reduces the FPS impact). This is because you could otherwise see weird visual behavior such as the block being broken but not actually disappearing until half a second later. If that behavior is fine for you, enabling that option may help.
