### ISSUE TITLE
[Crash] Mod crashing

### ISSUE THREAD

**Issue by ForestLive6** [embeddedt/ModernFix#130]
Minecraft 1.16.5
Forge 36.2.39
modernfix-fabric-5.0.1+mc1.16.5.jar
There are two instances of mods crashing. 
1) The first case, when using ModernFix + RandomPatches + Create mods, is that the mod crashes and creates a crashlog.
2) The second case, when there is a mod Immersive Industry + ModernFix, then the minecraft does not crash, but just does not start and there is a file latest. 

The first file is a bundle of ModernFix + RandomPatches + Create.
The second file is Immersive Industry + ModernFix.
[crash-2023-06-16_01.31.26-fml.txt](https://github.com/embeddedt/ModernFix/files/11763785/crash-2023-06-16_01.31.26-fml.txt)
[Latest.txt](https://github.com/embeddedt/ModernFix/files/11763790/Latest.txt)

**Comment by embeddedt** [comment]
I am pretty sure neither of these are ModernFix's fault. The first crash is caused by Connectivity, you need to follow its instructions to disable this feature of RandomPatches [here](https://legacy.curseforge.com/minecraft/mc-mods/connectivity).

The second crash is from Immersive Industry, it appears to be trying to modify a part of Minecraft's code and failing, but ModernFix doesn't touch that portion of the code, so I don't think it can be at fault. There must be another mod it conflicts with.

What has probably happened is that Forge has changed the order in which your mods are loading, since the number of mods in the game is now different. This can cause conflicts to appear that aren't actually triggered by the mod that was added.
