### ISSUE TITLE
[1.16.5] Crash upon creating world

### ISSUE THREAD

**Issue by IronworksProductions** [embeddedt/ModernFix#133]
I'm having this really odd crash when I attempt to create a world in 1.16.5 after adding ModernFix. It appears to be related to RoadRunner and ModernFix, as this error was not in play before I added ModernFix
Crash Report is linked below: https://bytebin.lucko.me/8y6KmxiZLR
Any ideas what might be causing this?

**Comment by embeddedt** [comment]
The mixin that causes the crash doesn't appear to be added by ModernFix so I am not sure why the crash doesn't occur without it. Can you send the full log file?

**Comment by IronworksProductions** [comment]
Sure, here's the full Latest: https://gist.github.com/MetaverseRPN/f7b0021bef2c1a698ecb2426d52851b5

**Comment by IronworksProductions** [comment]
Oop, actually that's the wrong one. It's this one: https://gist.github.com/MetaverseRPN/f8374d48af7824be64882892786de4cb

**Comment by embeddedt** [comment]
There are some strange errors at the beginning that suggest Roadrunner
isn't loading/applying its mixins correctly, however other modpacks use
Roadrunner and ModernFix together without problems so I doubt that is being
caused by ModernFix. (I have also never seen it occur when testing them
together independently.)

There is likely another mod that causes Roadrunner to break. Perhaps try
removing Essential or Not Enough Crashes and see if that changes anything.

If that doesn't work, my only other suggestion would be to remove
Roadrunner.

**Comment by IronworksProductions** [comment]
Hmm.... I just tried removing both Essential and Not Enough Crashes, I did just discover something odd, though. Those Mixin disable lines you mentioned at the start, that appears to be something Rubidium is doing: 
![image](https://github.com/embeddedt/ModernFix/assets/7560033/1bd4a55e-218e-4787-ad5b-f0ceb3f2c925)
Could it be Rubidium that's causing these issues?

**Comment by embeddedt** [comment]
That's very strange, it shouldn't be reading Roadrunner's mixins. Worth a
try I guess.

**Comment by IronworksProductions** [comment]
OML. I _really_ hope this wasn't what was causing the issue....
I had both Halogen and Rubidium installed.
Currently loading back up now, I'll update this if this actually fixed it.

**Comment by IronworksProductions** [comment]
Alright that fixed it. Sorry for wasting your time.
