### ISSUE TITLE
Changelogs not working properly

### ISSUE THREAD

**Issue by Zorklis** [embeddedt/ModernFix#138]
Just list what's the new thing you updated, it's confusing than helpful to have such an unorginized changelist.

**Comment by embeddedt** [comment]
The changelog generation system hasn't been working correctly since I changed my release publication strategy in light of the recent virus. I've been working towards fixing it but I have to make a release every time to test whether the fix has worked.

Normally it should only show the changes made since the previous release for that version, and so the list should be much shorter. However I most likely won't be manually writing a list of changes as that takes time away from development.

**Comment by embeddedt** [comment]
Changelogs should be working properly again. I may look into a basic release notes system to accompany them in future releases but no promises.
