### ISSUE TITLE
If this is 1.16+, where is 1.17?

### ISSUE THREAD

**Issue by the-r3dacted** [embeddedt/ModernFix#175]
If you're going to label this as 1.16+, that implies that there's a 1.17 version, which there isn't, or at least I can't find one.

**Comment by embeddedt** [comment]
You are correct, there is no 1.17 version. It would indeed be more accurate to say "all major modding versions since 1.16", but it would make the GitHub summary much longer, and 90% of players are not looking for 1.17 mods.

FWIW, the new long-form description I wrote on Modrinth says "most versions including and above 1.16 are supported", and I plan to update CurseForge with this description soon as well.

**Comment by the-r3dacted** [comment]
Could just say 1.16, 1.18+

Or just make a 1.17 version

**Comment by embeddedt** [comment]
> Could just say 1.16, 1.18+

Good idea, updated. Thanks.

> Or just make a 1.17 version

The number of players this would benefit is not worth the effort required to do this, especially considering that 1.17 is essentially a worse-performing version of 1.16 with the newer blocks added in (and I believe there are backport mods for 1.16 that add most of the blocks).
