### ISSUE TITLE
1.19.2 - 1.20.1 Add support for understanding blueprints or have it ignore `Minecolonies` warnings. Ultra Low Priority.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#177]
![Discord_ZQAdQrTmq0 1](https://github.com/embeddedt/ModernFix/assets/10351221/f690bc28-3664-425d-8567-497bcea25c23)
This would be most likely more cosmetic and spam removal (Even though its minor but in the future this mod should ignore "Minecolonies" file structure based warnings.)

**Comment by embeddedt** [comment]
From what I can tell there isn't a bug here. If the structure file was created in 1.18.2, it is considered outdated by ModernFix, since the game will need to use DFU to upgrade it to a 1.19.2 file. The warning should only be getting printed once per namespace, so it should add only one line in the log.
