### ISSUE TITLE
modernfix mixin causes crash on startup 1.16.5

### ISSUE THREAD

**Issue by DKLYNTLY** [embeddedt/ModernFix#219]
Corail tombstone and atum 2 both crash on startup due to moderfix mixins
[crash-2023-08-17_16.27.27-fml.txt](https://github.com/embeddedt/ModernFix/files/12373339/crash-2023-08-17_16.27.27-fml.txt)

**Comment by embeddedt** [comment]
Please provide the full `latest.log` file.

**Comment by embeddedt** [comment]
I also suspect this is not a ModernFix issue, as to my knowledge I do not modify BrewingRecipeRegistry, which is what is causing this crash.

**Comment by DKLYNTLY** [comment]
oh then i know what it is sorry

**Comment by DKLYNTLY** [comment]
the mod is called daves potioneering

**Comment by embeddedt** [comment]
Yep, adding that to my test instance resulted in the same crash. I also removed ModernFix and the crash persisted, so it doesn't appear to be caused by ModernFix.

After some quick isolation, it seems to be a conflict between Charm and Dave's Potioneering. The `Redirector always1(Lnet/minecraft/item/ItemStack;)I in davespotioneering.mixins.json:BrewingRecipeRegistryMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap davespotioneering.refmap.json` message goes away if either of these mods is removed.
