### ISSUE TITLE
[1.20.1] [NeoForge] Nether portal constantly generates new portal

### ISSUE THREAD

**Issue by waddon1** [embeddedt/ModernFix#254]
When entering/exiting a nether portal it constantly generates a new portal. I narrowed it down to this mod, not sure if it conflicting with something else or not.
[latest.log](https://github.com/embeddedt/ModernFix/files/12825564/latest.log)

**Comment by embeddedt** [comment]
Does this occur in a standalone NeoForge instance with ModernFix? If not it is likely a mod conflict.

**Comment by embeddedt** [comment]
I tried this morning and couldn't reproduce it a standalone instance - have you tried removing other server-related performance mods (e.g. Radium, Starlight) and checking whether it still occurs?

**Comment by waddon1** [comment]
I did some testing and I believe it only occurs when combined with Radium, need to test a little more though.

**Comment by embeddedt** [comment]
That would make sense - I believe Radium makes changes to the POI system, which has caused problems with villagers in the past. Nether portals use the same system so it's quite likely that portals would be broken at the same time. If this turns out to be the case, based on my past experience I would recommend not using that mod.

**Comment by waddon1** [comment]
Gonna close this as it was probably to do with Radium anyway and I fixed it by adding "mixin.ai.poi=false" to "Lithium.properties"

**Comment by embeddedt** [comment]
FYI - it sounds like this is fixed as of Radium [0.12.1](https://github.com/Reforged-Hub/radium-upstream/releases/tag/0.12.1%2Bgit.3e87e48).
