### ISSUE TITLE
With "Snow! Real Magic!” and "Continuity" compatibility

### ISSUE THREAD

**Issue by wsxiya** [embeddedt/ModernFix#283]
"mixin.perf.dynamic_ resources" is off by default and causes "Snow! Real Magic! "The overridden garss is not visible, if you turn on the "mixin.perf.dynamic_ resources" option, the connection texture of "Continuity" will not work, is there any solution?

**Comment by wsxiya** [comment]
minecraft1.20.1 forge47.1.3

**Comment by embeddedt** [comment]
Snow Real Magic indeed does not work with dynamic resources. This is because it doesn't use the Forge event for replacing models, instead relying on invasive patches into the model bakery. I will not fix this from my end, the mod should be changed to use proper APIs for this.

The Fabric version of ModernFix should work correctly with Continuity when dynamic resources is enabled. The Forge version is designed to work with Forge mods, not Fabric mods, so it may have issues. This issue should be reported to Connector.

**Comment by embeddedt** [comment]
I made some changes for the next release which simplify the code and also fix the issue with Continuity.
