### ISSUE TITLE
(Suggestion) Dynamic resources blacklist?

### ISSUE THREAD

**Issue by mosharky** [embeddedt/ModernFix#284]
Is that possible at all? Some mods, like the Embers Rekindled 1.20 port, still use baked models which aren't compatible with dynamic resources, so it'd be nice to maybe exclude them as a config option or something.

**Comment by embeddedt** [comment]
The config system is not structured in a way that allows adding a blacklist option easily, and I also dislike the idea of requiring users to blacklist their mods manually. I will instead add Embers to the internal list of mods that should have a workaround applied.

**Comment by mosharky** [comment]
Ah okay, thanks!

**Comment by embeddedt** [comment]
Embers pipes should work correctly as of 5.9.1.

**Comment by mosharky** [comment]
<3

**Comment by RCXcrafter** [comment]
I don't know what your policy is on compatibility with older versions of mods but embers rekindled now uses a custom loader to load its pipe models instead of the ModifyBakingResult event. I've confirmed that the pipes render properly with modernfix 5.9.0 (dynamic resources enabled) and embers rekindled 1.0.3. If you want you can remove the workaround for embers, if not, leaving it in will do no harm.

**Comment by mosharky** [comment]
This fixed a crash with Cobblemon too by the way 😉
