### ISSUE TITLE
Stitcher silently creates texture atlases that are too large

### ISSUE THREAD

**Issue by YeetboiPro** [embeddedt/ModernFix#384]
### Bug Description

LandK Tiles & LandK Bricks Installed with Modernfix across all 1.20.1 versions causes the mod loading screen to get stuck without freezing

### Reproduction Steps

Install LandK Tiles, LandK Bricks, and the latest 1.20.1 version of ModernFix

### Log File

Game doesn't load

**Comment by embeddedt** [comment]
I believe the reason this happens is that these mods register a very high quantity of large block textures. In vanilla, this causes a crash if your GPU cannot handle a texture that large. However, ModernFix's optimized texture stitcher appears to just silently create a large texture anyway, which is likely the problem. This will be fixed in the next release.

**Comment by embeddedt** [comment]
The stitcher has been fixed to emulate vanilla behavior in 5.16.0.
