### ISSUE TITLE
1.20.1 server crashes and blames modernfix

### ISSUE THREAD

**Issue by lolpowerluke** [embeddedt/ModernFix#402]
### Bug Description

server crashed unexpectedly

### Reproduction Steps

I have no idea, I was doing some exploration to find sapplings and the server crashed

### Log File

[crash-2024-05-09_11.41.38-server.txt](https://github.com/embeddedt/ModernFix/files/15260583/crash-2024-05-09_11.41.38-server.txt)

### Versions
Mod: 5.17.0+mc1.20.1
Forge: 1.20.1-47.2.17
OS: Windows 11 Home 23H2 Build 22631.3527

**Comment by embeddedt** [comment]
The Forge crash report analyzer is incorrect (as it usually is with performance mods); the issue is most likely that one of your mods accesses structure data on the wrong thread, which is unsafe and will cause random crashes like this. Unfortunately the crash does not give an indication as to which mod is really the problem.

**Comment by lolpowerluke** [comment]
could the server log help with finding the problem?

**Comment by lolpowerluke** [comment]
[2024-05-09-2.log](https://github.com/embeddedt/ModernFix/files/15263837/2024-05-09-2.log)
here is the server log in case u want to look through it
