### ISSUE TITLE
Freeze & Log Spam

### ISSUE THREAD

**Issue by Fyoncle** [embeddedt/ModernFix#411]
### Bug Description

Insane 4 Minutes Freeze When Using Locate Command and then watch dog spam and stuff

### Reproduction Steps

Just happened after the 5.18.0 update.

I use Fabric 1.20.1

### Log File

https://mclo.gs/CyLGGIR

**Comment by embeddedt** [comment]
The lag is being caused by chunk generation from the game trying to locate structures, and the log spam is the UWRAD mod reporting that `moremobvariants` is accessing a random number generator from the wrong thread. This looks highly unlikely to be a ModernFix bug.

**Comment by Fyoncle** [comment]
> The lag is being caused by chunk generation from the game trying to locate structures, and the log spam is the UWRAD mod reporting that `moremobvariants` is accessing a random number generator from the wrong thread. This looks highly unlikely to be a ModernFix bug.

Oh? bruh.

**Comment by Fyoncle** [comment]
So which mod is the reason of locate command lag? (ONLY HAPPENS WHEN LOCATING CHOICETHEOREM'S VILLAGE MOD'S VILLAGES.)

**Comment by embeddedt** [comment]
I believe it is usually the datapack/mod whose structure you are trying to locate, although I am not too familiar with this area of the code. If it only happens when locating ChoiceTheorem villages I would perhaps reach out to them about it.

Regardless, it is not something I believe ModernFix is causing, nor can I directly solve on my end - there was a change a few updates back to help with the efficiency of `/locate` for certain problematic structures (like buried treasure) but that is probably not relevant here.
