### ISSUE TITLE
Crash with Biome Particle Weather [Forge 1.20.1]

### ISSUE THREAD

**Issue by Mi6kbuttface** [embeddedt/ModernFix#416]
### Bug Description

I was playing on a private Minecraft modpack server with friends when it started to rain, and everyone, all the clients, and the server crashed and spat out a crash log mentioning ModernFix and BiomeParticleWeathercrash log

### Reproduction Steps

Step 1. Install ModernFix on a client and server
Step 2. On the client install Biome particle Weather
Step 3. set the weather to rain
Step 4. Crash

### Log File

My Client
[crash-2024-06-12_02.46.12-client.txt](https://github.com/user-attachments/files/15799714/crash-2024-06-12_02.46.12-client.txt)

**Comment by embeddedt** [comment]
`Registry Object not present` crashes usually indicate that the client & server have different mods or configs; make sure that the same mods are installed on both sides. Forge's crash report analyzer is poorly designed and blames ModernFix for this crash due to an optimization it makes to registry object handling.
