### ISSUE TITLE
A crash when opening a item select screen in certain mods with sinytra installed

### ISSUE THREAD

**Issue by Aabyonis** [embeddedt/ModernFix#445]
### Bug Description

note: even though is a older crash log i did test with the newer modernfix and it still happens and
this is a redirected issue from sinytra connector's discord, bcz i thought it might be connector mod causing issues they told me  to check in with the modernfix's author aswell.

when i try to open a screen where i have to select a block as an icon for a quest in the questing mod "heracles"
and also happens when i want to add a block to the advanced xray mod.

### Reproduction Steps

"when i try to open a screen where i have to select a block as an icon for a quest in the questing mod "heracles"
and also happens when i want to add a block to the advanced xray mod" quoting this again

### Log File

[xray crash.txt](https://github.com/user-attachments/files/16400435/xray.crash.txt)

**Comment by embeddedt** [comment]
The crash doesn't appear to be caused by ModernFix; Forge just blames it because it optimizes `getDelegateOrThrow` (and the Forge crash report analyzer is highly misleading for performance mods). The optimization should not be capable of triggering a `StackOverflowError`, so I think the issue lies with a different mod.
