### ISSUE TITLE
Blast Search Trees incompatible with EMI

### ISSUE THREAD

**Issue by Mqony** [embeddedt/ModernFix#468]
### Bug Description

EMI is gradually replacing JEI and REI, I think it would be very helpful if you could add compatibility between EMI and ModernFix's Blast search trees feature. Right now, both Creative and EMI utilize their search features at the same time causing very slow Creative menu loading with a lot of mods. I turned on force blast search trees, and it's MUCH faster. However, Creative Search doesn't load as there isn't compatibility between search trees and EMI.

### Reproduction Steps

Turn on Blast Search Trees Force feature and with EMI.

### Log File

(Not necessary but here it is anyway)
[latest.log](https://github.com/user-attachments/files/17248728/latest.log)

**Comment by embeddedt** [comment]
This cannot be added until https://github.com/emilyploszaj/emi/pull/496 or something similar is merged on EMI's end. Emi has expressed interest in looking into it when she has time.

Note, however, that `blast_search_trees` is gone in 1.21+ as it doesn't provide as much benefit due to internal changes in Minecraft.
